name: wait_a_minute
description: "고객 대기 감지 시스템 - 파란불빛 모니터링 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Essential dependencies only
  provider: ^6.1.1            # State management
  uuid: ^4.2.1                # Unique device IDs
  shared_preferences: ^2.2.2  # Local data storage
  
  # Permission handling
  permission_handler: ^11.3.1  # Handle device permissions
  
  # Camera functionality
  camera: ^0.10.5+9            # Camera access and preview
  wakelock_plus: ^1.2.5        # Keep screen awake during monitoring
  
  # Notifications
  flutter_local_notifications: ^17.2.4  # Local push notifications
  
  # Firebase for realtime database and auth
  firebase_core: ^4.0.0                # Firebase core
  firebase_database: ^12.0.0           # Firebase Realtime Database
  firebase_auth: ^6.0.0                # Firebase Authentication

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true